<?php
/**
 * Admin assets for CyberSource payment integration
 */
?>
<link rel="stylesheet" type="text/css" href="<?= $this->getViewFileUrl('CyberSource_Payment::css/order.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->getViewFileUrl('CyberSource_Payment::css/payment.css') ?>" />

<script type="text/javascript" src="<?= $this->getViewFileUrl('CyberSource_Payment::js/cybersource.js') ?>"></script>
<script type="text/javascript" src="<?= $this->getViewFileUrl('CyberSource_Payment::js/payment.js') ?>"></script>
<script type="text/javascript" src="<?= $this->getViewFileUrl('CyberSource_Payment::js/browser.js') ?>"></script>
<script type="text/javascript" src="<?= $this->getViewFileUrl('CyberSource_Payment::js/order.js') ?>"></script>
