<?php
$code = $block->escapeHtml($block->getMethodCode());
$method = $block->getMethod();
$controller = $block->escapeHtml($block->getRequest()->getControllerName());

/** @var CyberSource\Payment\Helper\Data $helper */
$helper = $this->helper('CyberSource\Payment\Helper\Data');
$orderUrl = $block->escapeUrl($helper->getPlaceOrderAdminUrl());
$tokens = $helper->getTokens($method->getStore());
$defaultPaymentAction = $method->getConfigPaymentAction();
$captureContextUrl = $block->escapeUrl($block->getUrl('cybersourceadmin/order/capturecontextrequest', [
    '_secure' => $block->getRequest()->isSecure()
]));
?>

 <fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtmlAttr($code) ?>" style="display:none;">
    <div class="admin__field _required">
        <div class="admin__field-control">
            <?php if (!empty($tokens)) : ?>
            <table class="admin__table-secondary">
                <?php foreach ($tokens as $token) : ?>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Token')); ?></th>
                        <td><input type="radio" name="payment[token]" value="<?php echo $block->escapeHtml($token['token_id']); ?>">
                            <?php echo $block->escapeHtml($token['cc_number']); ?>
                        </td>
                    </tr>
                    <?php if ($helper->getGatewayConfig()->isCVVEnabled()) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('CVV')); ?></th>
                            <td><input type="number" name="payment[cvv]" maxlength="4"></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </table>
            <?php else : ?>
                <?php echo $block->escapeHtml(__('No Tokens for this customer')); ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="admin__field">
        <div class="admin__field-control">
            <div id="buttonPaymentListContainer"></div>
            <div id="embeddedPaymentContainer"></div>
            <input type="hidden" id="cybersource-payment-token" name="payment[additional_data][paymentToken]" value="" />
        </div>
    </div>
    <div class="admin__field">
        <label class="admin__field-label" for="cybersource-payment-action">
            <span><?= $block->escapeHtml(__('Payment Action')) ?></span>
        </label>
        <div class="admin__field-control">
            <select class="admin__control-select" name="payment[additional_data][payment_action]" id="cybersource-payment-action">
                <option value="authorize" <?= $defaultPaymentAction === 'authorize' ? 'selected="selected"' : '' ?>>
                    <?= $block->escapeHtml(__('Authorize')) ?>
                </option>
                <option value="authorize_capture" <?= $defaultPaymentAction === 'authorize_capture' ? 'selected="selected"' : '' ?>>
                    <?= $block->escapeHtml(__('Authorize and Capture')) ?>
                </option>
            </select>
        </div>
    </div>
</fieldset>
<script>
    require([
        'prototype',
        'Magento_Sales/order/create/scripts',
        "Magento_Sales/order/create/form",
        'CyberSource_Payment/js/cybersource'
    ], function(){
        var visaacceptance = new Cybersource(
            '<?php /* @noEscape */ echo $code; ?>',
            '<?php /* @noEscape */ echo $controller; ?>',
            '<?php /* @noEscape */ echo $orderUrl; ?>',
            '<?php echo $block->escapeUrl($block->getUrl('*/*/save', [
                '_secure' => $block->getRequest()->isSecure()
            ]));?>',
            '<?php /* @noEscape */ echo $captureContextUrl; ?>',
            '#cybersource-payment-token');
    });
</script>
