<?php
$code = $block->escapeHtml($block->getMethodCode());
$controller = $block->escapeHtml($block->getRequest()->getControllerName());
/** @var CyberSource\Payment\Helper\Data $helper */
$helper = $this->helper('CyberSource\Payment\Helper\Data');
$orderUrl = $block->escapeUrl($helper->getPlaceOrderAdminUrl());
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtmlAttr($code) ?>">
    <div class="admin__field _required">
        <div class="admin__field-control">
            <div id="buttonPaymentListContainer"></div>
            <div id="embeddedPaymentContainer"></div>
        </div>
    </div>
</fieldset>

<?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
    ->setTemplate('CyberSource_Payment::device_data_collection.phtml')
    ->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
    ->setTemplate('CyberSource_Payment::stepup_authentication.phtml')
    ->toHtml(); ?>

<script>
    require([
        'prototype',
        'Magento_Sales/order/create/scripts',
        'Magento_Sales/order/create/form',
        'CyberSource_Payment/js/cybersource',
        'CyberSource_Payment/js/unified-checkout-admin'
    ], function(){
        var visaacceptance = new Cybersource(
            '<?php /* @noEscape */ echo $code; ?>',
            '<?php /* @noEscape */ echo $controller; ?>',
            '<?php /* @noEscape */ echo $orderUrl; ?>',
            '<?php echo $block->escapeUrl($block->getUrl('*/*/save', [
                '_secure' => $block->getRequest()->isSecure()
            ]));?>');

        require(['CyberSource_Payment/js/unified-checkout-admin'], function (UCAdmin) {
            UCAdmin({
                captureContextUrl: '<?php echo $block->getUrl('cybersourceadmin/capturecontextrequest'); ?>',
                transientUrl: '<?php echo $block->getUrl('cybersourceadmin/transientdataretrival'); ?>',
                payerAuthUrl: '<?php echo $block->getUrl('cybersourceadmin/pasetup'); ?>',
                methodCode: '<?php /* @noEscape */ echo $code; ?>'
            });
        });
    });
</script>
